insert into team(name)values ('Chelsea');
insert into team(name)values ('Arsenal');
insert into team(name)values ('Manchester United');
insert into team(name)values ('Manchester City');
insert into team(name)values ('Liverpool');
insert into team(name)values ('Tottenham');
insert into team(name)values ('Real Madryt');
insert into team(name)values ('Barcelona');
insert into team(name)values ('Bayern Monachium');
insert into team(name)values ('Juventus');
insert into team(name)values ('AC Milan');
